{
  "id": "EUVD-2021-2016",
  "enisaUuid": "83394436-33a4-3bb8-a55a-3cbaf9589cc4",
  "description": "An issue was discovered in the stack_dst crate before 0.6.1 for Rust. Because of the push_inner behavior, a double free can occur upon a val.clone() panic.",
  "datePublished": "Mar 5, 2021, 8:39:46 AM",
  "dateUpdated": "Aug 3, 2024, 9:33:17 PM",
  "baseScore": 9.8,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
  "references": [
    "https://nvd.nist.gov/vuln/detail/CVE-2021-28034",
    "https://github.com/thepowersgang/stack_dst-rs/issues/5",
    "https://github.com/thepowersgang/stack_dst-rs/commit/2a4d538",
    "https://github.com/thepowersgang/stack_dst-rs/commit/2a4d53809e3000f40085f2b229b6b1a33759881d",
    "https://github.com/thepowersgang/stack_dst-rs",
    "https://rustsec.org/advisories/RUSTSEC-2021-0033.html"
  ],
  "aliases": [
    "CVE-2021-28034",
    "GHSA-8mjx-h23h-w2pg"
  ],
  "assigner": "mitre",
  "epss": 0.42,
  "enisaIdProduct": [
    {
      "id": "938adba8-85a6-39b7-aaad-8f8ef94e9522",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "a965e4b8-1234-3f93-adc9-fad4db60060b",
      "vendor": {
        "name": "n/a"
      }
    }
  ]
}