{
  "id": "EUVD-2017-0002",
  "enisaUuid": "8dcfaf86-b43f-3790-adce-d1ae612dc86d",
  "description": "The user module in ansible before 1.6.6 allows remote authenticated users to execute arbitrary commands.",
  "datePublished": "Jun 8, 2017, 6:29:00 PM",
  "dateUpdated": "Jul 2, 2021, 2:41:33 AM",
  "baseScore": 8.8,
  "baseScoreVersion": "3.0",
  "baseScoreVector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
  "references": [
    "https://github.com/ansible/ansible/commit/8ed6350e65c82292a631f08845dfaacffe7f07f5",
    "https://bugzilla.redhat.com/show_bug.cgi?id=1335551",
    "https://nvd.nist.gov/vuln/detail/CVE-2014-3498",
    "https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2017-2.yaml",
    "https://www.suse.com/security/cve/CVE-2014-3498.html"
  ],
  "aliases": [
    "CVE-2014-3498",
    "PYSEC-2017-2"
  ],
  "assigner": "redhat",
  "epss": 0.55,
  "enisaIdProduct": [
    {
      "id": "359ced61-6c36-3634-8dd0-674066e50c5a",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "b227613d-f5e6-3d59-b704-c8a172718763",
      "vendor": {
        "name": "n/a"
      }
    }
  ],
  "cve": "CVE-2014-3498"
}