{
  "id": "EUVD-2021-0155",
  "enisaUuid": "2fd029b2-80cf-3a1f-bc2e-6f5240ea5ae1",
  "description": "OctoPrint before 1.6.0 allows XSS because API error messages include the values of input parameters.",
  "datePublished": "May 11, 2021, 2:15:00 PM",
  "dateUpdated": "May 11, 2021, 3:18:00 PM",
  "baseScore": 6.1,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
  "references": [
    "https://github.com/OctoPrint/OctoPrint/releases/tag/1.6.0",
    "https://www.brzozowski.io",
    "https://octoprint.org/blog/2021/04/27/new-release-1.6.0/",
    "https://nvd.nist.gov/vuln/detail/CVE-2021-32561",
    "https://github.com/pypa/advisory-database/tree/main/vulns/octoprint/PYSEC-2021-30.yaml",
    "https://www.brzozowski.io/web-applications/2021/05/11/the-insecure-story-of-octoprint.html"
  ],
  "aliases": [
    "CVE-2021-32561",
    "PYSEC-2021-30"
  ],
  "assigner": "mitre",
  "epss": 0.31,
  "enisaIdProduct": [
    {
      "id": "5ef08cec-b46d-38e1-bad8-839399d2b876",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "0a294ed7-7dc8-3dcb-8ba4-870816e5ba37",
      "vendor": {
        "name": "n/a"
      }
    }
  ],
  "cve": "CVE-2021-32561"
}