{
  "id": "EUVD-2022-0199",
  "description": "path_getbbox in path.c in Pillow before 9.0.0 improperly initializes ImagePath.Path.",
  "datePublished": "Jan 10, 2022, 2:12:00 PM",
  "dateUpdated": "Jan 24, 2022, 11:48:19 PM",
  "baseScore": 6.5,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
  "references": [
    "https://github.com/python-pillow/Pillow/blob/c5d9223a8b5e9295d15b5a9b1ef1dae44c8499f3/src/path.c#L331",
    "https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#fixed-imagepath-path-array-handling",
    "https://lists.debian.org/debian-lts-announce/2022/01/msg00018.html",
    "https://github.com/advisories/GHSA-pw3c-h7wp-cvhx",
    "https://nvd.nist.gov/vuln/detail/CVE-2022-22815",
    "https://github.com/python-pillow/Pillow/pull/5920",
    "https://github.com/python-pillow/Pillow/commit/1e092419b6806495c683043ab3feb6ce264f3b9c",
    "https://github.com/python-pillow/Pillow/commit/c48271ab354db49cdbd740bc45e13be4f0f7993c",
    "https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2022-8.yaml",
    "https://github.com/python-pillow/Pillow/blob/e8ab5640774716c5486d3cb05167f74f742ad6ef/CHANGES.rst?plain=1#L1187",
    "https://www.debian.org/security/2022/dsa-5053",
    "https://www.suse.com/security/cve/CVE-2022-22815.html",
    "https://ubuntu.com/security/CVE-2022-22815",
    "https://advisories.mageia.org/CVE-2022-22815.html",
    "https://access.redhat.com/errata/RHSA-2022:0643",
    "https://security.gentoo.org/glsa/202211-10"
  ],
  "aliases": [
    "CVE-2022-22815",
    "GHSA-pw3c-h7wp-cvhx",
    "PYSEC-2022-8"
  ],
  "assigner": "mitre",
  "epss": 0.09,
  "enisaIdProduct": [
    {
      "id": "258b614d-c445-3ba7-ac9a-ca22f9023140",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "44b0ab64-d781-3f30-8d38-3951d1f4fb1b",
      "vendor": {
        "name": "n/a"
      }
    }
  ],
  "cve": "CVE-2022-22815"
}