{
  "id": "EUVD-2023-1077",
  "enisaUuid": "b9bae9a6-9f69-386c-8366-cb78471d55f8",
  "description": "An infinite recursion is triggered in Jettison when constructing a JSONArray from a Collection that contains a self-reference in one of its elements. This leads to a StackOverflowError exception being thrown.\n\n",
  "datePublished": "Mar 16, 2023, 8:59:51 PM",
  "dateUpdated": "Feb 26, 2025, 3:02:24 PM",
  "baseScore": 5.9,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
  "references": [
    "https://nvd.nist.gov/vuln/detail/CVE-2023-1436",
    "https://github.com/jettison-json/jettison/issues/60",
    "https://github.com/jettison-json/jettison/pull/62",
    "https://github.com/jettison-json/jettison",
    "https://github.com/jettison-json/jettison/releases/tag/jettison-1.5.4",
    "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911",
    "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911/"
  ],
  "aliases": [
    "CVE-2023-1436",
    "GHSA-q6g2-g7f3-rr83"
  ],
  "assigner": "JFROG",
  "epss": 0.02,
  "enisaIdProduct": [
    {
      "id": "f427290c-e1b6-3aa2-acb1-f1bd6380000b",
      "product": {
        "name": "Jettison"
      },
      "product_version": "0 <1.5.4"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "3718e3cc-74d0-341b-abfe-7808ad733d99",
      "vendor": {
        "name": "Jettison"
      }
    }
  ]
}