{
  "id": "EUVD-2016-9518",
  "enisaUuid": "e463729a-f9fb-32bc-a5b9-83532d13b712",
  "description": "The _dwarf_get_size_of_val function in libdwarf/dwarf_util.c in Libdwarf before 20161124 allows remote attackers to cause a denial of service (out-of-bounds read) by calling the dwarfdump command on a crafted file.",
  "datePublished": "May 13, 2022, 1:03:23 AM",
  "dateUpdated": "Apr 20, 2025, 3:32:57 AM",
  "baseScore": 6.5,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
  "references": [
    "https://www.suse.com/security/cve/CVE-2016-8679.html",
    "https://security.archlinux.org/CVE-2016-8679",
    "https://bugzilla.redhat.com/show_bug.cgi?id=1385689",
    "https://blogs.gentoo.org/ago/2016/10/06/libdwarf-heap-based-buffer-overflow-in-_dwarf_get_size_of_val-dwarf_util-c/",
    "http://www.securityfocus.com/bid/93601",
    "http://www.openwall.com/lists/oss-security/2016/10/16/3",
    "https://nvd.nist.gov/vuln/detail/CVE-2016-8679"
  ],
  "aliases": [
    "CVE-2016-8679",
    "GSD-2016-8679"
  ],
  "assigner": "mitre",
  "epss": 0.75,
  "enisaIdProduct": [
    {
      "id": "b26e2afe-e97f-374f-a3c1-8dda47840fc1",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "650492c7-4b3e-3f67-9d0b-a0e8ec1d9c7d",
      "vendor": {
        "name": "n/a"
      }
    }
  ]
}