{
  "id": "EUVD-2020-0051",
  "enisaUuid": "f799895a-81c5-3833-877e-42790514a497",
  "description": "The Beaker library through 1.11.0 for Python is affected by deserialization of untrusted data, which could lead to arbitrary code execution.",
  "datePublished": "Jun 26, 2020, 8:15:00 PM",
  "dateUpdated": "Jul 25, 2021, 11:34:27 PM",
  "baseScore": 6.8,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:A/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
  "references": [
    "https://github.com/bbangert/beaker/issues/191",
    "https://bugzilla.redhat.com/show_bug.cgi?id=1850105",
    "https://www.openwall.com/lists/oss-security/2020/05/14/11",
    "https://github.com/advisories/GHSA-3cwm-7jmm-774w",
    "https://nvd.nist.gov/vuln/detail/CVE-2013-7489",
    "https://github.com/pypa/advisory-database/tree/main/vulns/beaker/PYSEC-2020-216.yaml",
    "https://www.suse.com/security/cve/CVE-2013-7489.html"
  ],
  "aliases": [
    "CVE-2013-7489",
    "GHSA-3cwm-7jmm-774w",
    "PYSEC-2020-216"
  ],
  "assigner": "mitre",
  "epss": 0.05,
  "enisaIdProduct": [
    {
      "id": "b333fd3e-a42b-3dbc-8eeb-3a1ca637935c",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "de63cf62-c1c4-35ce-bd63-0c8e5b55bcc0",
      "vendor": {
        "name": "n/a"
      }
    }
  ],
  "cve": "CVE-2013-7489"
}