{
  "id": "EUVD-2021-9346",
  "enisaUuid": "94c1088b-55cf-38ac-aa80-31f9e56aff20",
  "description": "An issue has been discovered in GitLab CE/EE affecting all versions starting with 12.6. Under a special condition it was possible to access data of an internal repository through a public project fork as an anonymous user.",
  "datePublished": "Apr 2, 2021, 4:22:37 PM",
  "dateUpdated": "Aug 3, 2024, 6:37:18 PM",
  "baseScore": 5.9,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
  "references": [
    "https://security.archlinux.org/CVE-2021-22200",
    "https://gitlab.com/gitlab-org/gitlab/-/issues/247523",
    "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22200.json"
  ],
  "aliases": [
    "CVE-2021-22200",
    "GSD-2021-22200"
  ],
  "assigner": "GitLab",
  "epss": 0.17,
  "enisaIdProduct": [
    {
      "id": "049b88b1-5e34-3440-92de-ca7ae8f68e60",
      "product": {
        "name": "GitLab"
      },
      "product_version": "13.10, <13.10.1"
    },
    {
      "id": "0f74a024-efd0-35b2-898a-0df83e52fb02",
      "product": {
        "name": "GitLab"
      },
      "product_version": "13.9, <13.9.5"
    },
    {
      "id": "b79604c1-46d0-3f4a-9739-6a35488e73ba",
      "product": {
        "name": "GitLab"
      },
      "product_version": "12.6, <13.8.7"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "295f1427-2a2a-3fd4-8b08-3c1233afe77a",
      "vendor": {
        "name": "GitLab"
      }
    }
  ]
}