{
  "id": "EUVD-2020-30696",
  "enisaUuid": "9b1d45f8-9afd-3a0b-ab76-34462e5bfa87",
  "description": "This issue was addressed with improved checks. This issue is fixed in iOS 13.6 and iPadOS 13.6. A remote attacker may be able to cause a denial of service.",
  "datePublished": "Oct 16, 2020, 4:48:15 PM",
  "dateUpdated": "Aug 4, 2024, 10:43:05 AM",
  "baseScore": 7.5,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
  "references": [
    "https://support.apple.com/HT211288"
  ],
  "aliases": [
    "CVE-2020-9917",
    "GSD-2020-9917"
  ],
  "assigner": "apple",
  "epss": 0.6,
  "enisaIdProduct": [
    {
      "id": "1284140a-ad2c-35c1-99c0-b750fb5ed847",
      "product": {
        "name": "IOS"
      },
      "product_version": "unspecified <iOS 13.6 and iPadOS 13.6"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "15c0badc-8941-3a5c-9bdd-e21cd43e89a8",
      "vendor": {
        "name": "Apple"
      }
    }
  ]
}