{
  "id": "EUVD-2018-0122",
  "enisaUuid": "dea0c764-e829-3716-82af-8f93d99ed263",
  "description": "OpenKMIP PyKMIP version All versions before 0.8.0 contains a CWE 399: Resource Management Errors (similar issue to CVE-2015-5262) vulnerability in PyKMIP server that can result in DOS: the server can be made unavailable by one or more clients opening all of the available sockets. This attack appear to be exploitable via A client or clients open sockets with the server and then never close them. This vulnerability appears to have been fixed in 0.8.0.",
  "datePublished": "Dec 20, 2018, 5:29:00 PM",
  "dateUpdated": "Jun 10, 2021, 6:50:52 AM",
  "baseScore": 6.5,
  "baseScoreVersion": "3.0",
  "baseScoreVector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
  "references": [
    "https://github.com/OpenKMIP/PyKMIP/issues/430",
    "https://github.com/advisories/GHSA-gfv6-cj92-g3hx",
    "https://nvd.nist.gov/vuln/detail/CVE-2018-1000872",
    "https://github.com/OpenKMIP/PyKMIP/commit/3a7b880bdf70d295ed8af3a5880bab65fa6b3932",
    "https://github.com/pypa/advisory-database/tree/main/vulns/pykmip/PYSEC-2018-22.yaml",
    "https://www.suse.com/security/cve/CVE-2018-1000872.html"
  ],
  "aliases": [
    "CVE-2018-1000872",
    "GHSA-gfv6-cj92-g3hx",
    "PYSEC-2018-22"
  ],
  "assigner": "mitre",
  "epss": 0.28,
  "enisaIdProduct": [
    {
      "id": "01c67f71-1a60-3ed3-a27c-ae2349f7c768",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "37dddc47-661b-39c0-88a7-f294658e2ff3",
      "vendor": {
        "name": "n/a"
      }
    }
  ]
}