{
  "id": "EUVD-2025-31095",
  "description": "An issue in the component torch.linalg.lu of pytorch v2.8.0 allows attackers to cause a Denial of Service (DoS) when performing a slice operation.",
  "datePublished": "Sep 25, 2025, 3:30:25 PM",
  "dateUpdated": "Sep 29, 2025, 6:33:12 PM",
  "baseScore": 7.5,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
  "references": [
    "https://github.com/pytorch/pytorch/issues/151401",
    "https://gist.github.com/shaoyuyoung/0e7d2a586297ae9c8ed14d8706749efc",
    "https://nvd.nist.gov/vuln/detail/CVE-2025-55551"
  ],
  "aliases": [
    "CVE-2025-55551"
  ],
  "assigner": "mitre",
  "epss": 0.05,
  "enisaIdProduct": [
    {
      "id": "4bc1ce51-ba93-36ba-987b-508a2cbf4e45",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "db7d29f1-80c6-3afc-a0e1-982885ca899a",
      "vendor": {
        "name": "n/a"
      }
    }
  ],
  "cve": "CVE-2025-55551"
}