{
  "id": "EUVD-2022-0094",
  "enisaUuid": "6dffa014-6f8c-30a1-a16a-465c77a690ce",
  "description": "In Django 3.2 before 3.2.16, 4.0 before 4.0.8, and 4.1 before 4.1.2, internationalized URLs were subject to a potential denial of service attack via the locale parameter, which is treated as a regular expression.",
  "datePublished": "Oct 16, 2022, 12:00:00 AM",
  "dateUpdated": "Feb 13, 2025, 4:33:04 PM",
  "baseScore": 7.5,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
  "references": [
    "https://docs.djangoproject.com/en/4.0/releases/security/",
    "https://github.com/django/django/commit/5b6b257fa7ec37ff27965358800c67e2dd11c924",
    "https://www.djangoproject.com/weblog/2022/oct/04/security-releases/",
    "https://groups.google.com/forum/#!forum/django-announce",
    "https://nvd.nist.gov/vuln/detail/CVE-2022-41323",
    "https://github.com/django/django/commit/23f0093125ac2e553da6c1b2f9988eb6a3dd2ea1",
    "https://github.com/django/django/commit/9d656ea51d9ea7105c0c0785783ac29d426a7d25",
    "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-304.yaml",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKYVMMR7RPM6AHJ2SBVM2LO6D3NGFY7B",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZS4G6NSZWPTVXMMZHJOJVQEPL3QTO77",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YJB6FUBBLVKKG655UMTLQNN6UQ6EDLSP",
    "https://security.netapp.com/advisory/ntap-20221124-0001",
    "https://www.debian.org/security/2022/dsa-5254",
    "https://www.suse.com/security/cve/CVE-2022-41323.html",
    "https://ubuntu.com/security/CVE-2022-41323",
    "https://security.archlinux.org/CVE-2022-41323",
    "https://advisories.mageia.org/CVE-2022-41323.html",
    "https://access.redhat.com/errata/RHSA-2023:0742",
    "https://groups.google.com/forum/#%21forum/django-announce",
    "https://security.netapp.com/advisory/ntap-20221124-0001/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZS4G6NSZWPTVXMMZHJOJVQEPL3QTO77/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FKYVMMR7RPM6AHJ2SBVM2LO6D3NGFY7B/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YJB6FUBBLVKKG655UMTLQNN6UQ6EDLSP/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"
  ],
  "aliases": [
    "CVE-2022-41323",
    "PYSEC-2022-304"
  ],
  "assigner": "mitre",
  "epss": 6.17,
  "enisaIdProduct": [
    {
      "id": "ecc7dcb7-138d-3537-a820-21fdb7141fa8",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "6c442555-15d6-3bf2-94dd-2de23307b4c6",
      "vendor": {
        "name": "n/a"
      }
    }
  ]
}