{
  "id": "EUVD-2024-29762",
  "enisaUuid": "54a75742-063a-3c26-a86d-219a940a533b",
  "description": "IBM App Connect Enterprise 11.0.0.1 through 11.0.0.25 and 12.0.1.0 through 12.0.12.0 integration nodes could allow an authenticated user to cause a denial of service due to an uncaught exception.  IBM X-Force ID:  289647.",
  "datePublished": "May 22, 2024, 6:34:39 PM",
  "dateUpdated": "Aug 2, 2024, 1:59:50 AM",
  "baseScore": 6.5,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
  "references": [
    "https://www.ibm.com/support/pages/node/7154607",
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/289647"
  ],
  "aliases": [
    "CVE-2024-31904",
    "GSD-2024-31904"
  ],
  "assigner": "ibm",
  "epss": 0.14,
  "enisaIdProduct": [
    {
      "id": "8beb801e-27d8-3a95-a5b7-1f5d311c4fa0",
      "product": {
        "name": "App Connect Enterprise"
      },
      "product_version": "11.0.0.1 \u226411.0.0.25"
    },
    {
      "id": "a13b8131-0bb6-392d-8537-65a549fa26c6",
      "product": {
        "name": "App Connect Enterprise"
      },
      "product_version": "12.0.1.0 \u226412.0.12.0"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "00ae4628-4b1b-38c9-9aff-c0a1fa7ff2ee",
      "vendor": {
        "name": "IBM"
      }
    }
  ]
}